In [22]:
%matplotlib inline
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

In [23]:
df = pd.read_csv("../Resources/eight_year_cycle.csv")
df.head()

,country_code,country_name,year,co2_normalized,merge_id,male_death_rate,female_death_rate,cigarette_sales,gdp_normalized,co2_emissions_-8,...,cigarette_sales_-2,cigarette_sales_-1,GDP_-8,GDP_-7,GDP_-6,GDP_-5,GDP_-4,GDP_-3,GDP_-2,GDP_-1
0,ARM,Armenia,1998,0.121883,ARM_1998,38.05,5.43,5.7,584.384267,0.697225,...,5.6,5.6,634.560413,572.161763,356.082212,347.466463,389.825287,441.894002,484.091641,501.156515
1,AUS,Australia,1968,0.017502,AUS_1968,45.00,5.74,8.8,2723.999484,0.011467,...,8.9,8.5,1810.510249,1877.509803,1854.552575,1967.014259,2131.277657,2280.902108,2343.706917,2579.986340
2,AUS,Australia,1969,0.018494,AUS_1969,46.75,5.66,8.9,2991.241889,0.011777,...,8.5,8.8,1877.509803,1854.552575,1967.014259,2131.277657,2280.902108,2343.706917,2579.986340,2723.999484
3,AUS,Australia,1970,0.019191,AUS_1970,47.79,7.18,9.1,3304.678667,0.012339,...,8.8,8.9,1854.552575,1967.014259,2131.277657,2280.902108,2343.706917,2579.986340,2723.999484,2991.241889
4,AUS,Australia,1971,0.019861,AUS_1971,49.28,7.53,8.9,3494.973309,0.013134,...,8.9,9.1,1967.014259,2131.277657,2280.902108,2343.706917,2579.986340,2723.999484,2991.241889,3304.678667

In [21]:
df = df.drop(columns=['country_code', 'merge_id'])
dummies = pd.get_dummies(df['country_name'])
merged_df = pd.merge(df, dummies, left_index=True, right_index=True)
merged_df = merged_df.drop(columns='country_name')

# Split our preprocessed data into our features and target arrays
y = (merged_df['male_death_rate'] + merged_df['female_death_rate']) /2 
X = merged_df.drop(columns=['male_death_rate', 'female_death_rate'])

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [24]:
df = df.drop(columns=['country_code', 'merge_id', 'country_name'])
merged_df = df

# Split our preprocessed data into our features and target arrays
y = (merged_df['male_death_rate'] + merged_df['female_death_rate']) /2 
X = merged_df.drop(columns=['male_death_rate', 'female_death_rate'])

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [25]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [26]:
regr = RandomForestRegressor().fit(X_train_scaled, y_train)
print(f'Training Score: {regr.score(X_train_scaled, y_train)}')
print(f'Testing Score: {regr.score(X_test_scaled, y_test)}')

Training Score: 0.974247876076364
Testing Score: 0.8467724745615395

In [28]:
X.columns

Index(['year', 'co2_normalized', 'cigarette_sales', 'gdp_normalized',
       'co2_emissions_-8', 'co2_emissions_-7', 'co2_emissions_-6',
       'co2_emissions_-5', 'co2_emissions_-4', 'co2_emissions_-3',
       'co2_emissions_-2', 'co2_emissions_-1', 'cigarette_sales_-8',
       'cigarette_sales_-7', 'cigarette_sales_-6', 'cigarette_sales_-5',
       'cigarette_sales_-4', 'cigarette_sales_-3', 'cigarette_sales_-2',
       'cigarette_sales_-1', 'GDP_-8', 'GDP_-7', 'GDP_-6', 'GDP_-5', 'GDP_-4',
       'GDP_-3', 'GDP_-2', 'GDP_-1'],
      dtype='object')

In [27]:
regr.predict()

TypeError: predict() missing 1 required positional argument: 'X'